# Viewport settings
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 600
SCREEN_TITLE = "AI Car"

# Physics steps
DT = 1 / 80.0

# Map settings
HEIGHT = 500
WIDTH = SCREEN_WIDTH
DIV = 25
G_W = WIDTH // DIV
G_H = HEIGHT // DIV

# For Line
VERTICAL_LINE_GRADIENT = 1e5
